language: android
jdk: oraclejdk8
android:
  components:
    - build-tools-27.0.2
    - android 27
#    - extra-android-m2repository
#    - extra-android-support

script:
  ./gradlew connectedAndroidTest