language: android
jdk: oraclejdk8
android:
  components:
    - build-tools-27.0.2
    - android-27
    - platform-tools
#    - extra-android-m2repository
#    - extra-android-support

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
#  ./gradlew connectedAndroidTest
- "./gradlew assembleRelease"